# Generated by Django 3.2.6 on 2021-08-30 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default=2, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterModelTable(
            name='products',
            table='product',
        ),
    ]
