# Generated by Django 3.2.6 on 2021-09-06 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='category',
        ),
    ]
