# Generated by Django 3.2.6 on 2021-09-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_products_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categoy',
        ),
    ]
