# Generated by Django 3.2.7 on 2021-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.BooleanField(max_length=10, verbose_name='Estado'),
        ),
    ]
